/**
 * GameDataMappings.gs
 *
 * Static ID -> human-readable name lookups for SWGOH inventory data.
 * Generated from swgoh-utils/gamedata (equipment.json, material.json)
 * cross-referenced against Loc_ENG_US.txt.json, filtered to the IDs
 * present in this account's inventory export.
 *
 * Source: https://github.com/swgoh-utils/gamedata (community-maintained,
 * auto-updated from the live game data ~every 10 min after a game update)
 *
 * Regenerate by re-running the extraction process with a fresh inventory
 * export if you start seeing raw IDs show up as names (means new gear/mats
 * were added that weren't in this snapshot).
 */

const EQUIPMENT_NAMES = {
  "001": "Mk 1 BlasTech Weapon Mod",
  "002": "Mk 1 BAW Armor Mod",
  "003": "Mk 1 Neuro-Saav Electrobinoculars",
  "004": "Mk 1 TaggeCo Holo Lens",
  "005": "Mk 1 Nubian Security Scanner",
  "006": "Mk 1 Loronar Power Cell",
  "007": "Mk 1 Fabritech Data Pad",
  "008": "Mk 1 Arakyd Droid Caller",
  "009": "Mk 1 BioTech Implant",
  "010": "Mk 1 A/KT Stun Gun",
  "011": "Mk 1 CEC Fusion Furnace",
  "012": "Mk 1 Merr-Sonn Shield Generator",
  "013": "Mk 2 BlasTech Weapon Mod",
  "014": "Mk 2 BAW Armor Mod",
  "014Prototype": "Mk 2 BAW Armor Mod Prototype",
  "015": "Mk 2 Neuro-Saav Electrobinoculars",
  "015Prototype": "Mk 2 Neuro-Saav Electrobinoculars Prototype",
  "016": "Mk 2 TaggeCo Holo Lens",
  "017": "Mk 2 Nubian Security Scanner",
  "017Prototype": "Mk 2 Nubian Security Scanner Prototype",
  "018": "Mk 2 Loronar Power Cell",
  "019": "Mk 1 SoroSuub Keypad",
  "020": "Mk 1 Czerka Stun Cuffs",
  "021": "Mk 1 Chiewab Hypo Syringe",
  "021Prototype": "Mk 1 Chiewab Hypo Syringe Prototype",
  "022": "Mk 2 BioTech Implant",
  "023": "Mk 2 CEC Fusion Furnace",
  "024": "Mk 2 Merr-Sonn Shield Generator",
  "025": "Mk 3 BlasTech Weapon Mod",
  "026": "Mk 3 BAW Armor Mod",
  "027": "Mk 3 Neuro-Saav Electrobinoculars",
  "028": "Mk 3 TaggeCo Holo Lens",
  "028Prototype": "Mk 3 TaggeCo Holo Lens Prototype",
  "029": "Mk 3 Loronar Power Cell",
  "030": "Mk 2 Fabritech Data Pad",
  "031": "Mk 1 Nubian Design Tech",
  "031Prototype": "Mk 1 Nubian Design Tech Prototype",
  "032": "Mk 2 SoroSuub Keypad",
  "032Prototype": "Mk 2 SoroSuub Keypad Prototype",
  "033": "Mk 2 Arakyd Droid Caller",
  "034": "Mk 1 Sienar Holo Projector",
  "035": "Mk 2 Chiewab Hypo Syringe",
  "036": "Mk 3 BioTech Implant",
  "037Prototype": "Mk 4 BlasTech Weapon Mod Prototype",
  "039": "Mk 3 Nubian Security Scanner",
  "040Prototype": "Mk 4 Loronar Power Cell Prototype",
  "041": "Mk 3 Fabritech Data Pad",
  "042": "Mk 2 Nubian Design Tech",
  "043": "Mk 3 SoroSuub Keypad",
  "044": "Mk 4 BioTech Implant",
  "044Prototype": "Mk 4 BioTech Implant Prototype",
  "045": "Mk 2 A/KT Stun Gun",
  "046": "Mk 3 CEC Fusion Furnace",
  "047": "Mk 3 Merr-Sonn Shield Generator",
  "048": "Mk 1 Merr-Sonn Thermal Detonator",
  "049Prototype": "Mk 5 BlasTech Weapon Mod Prototype",
  "050Salvage": "Mk 4 BAW Armor Mod Salvage",
  "051Salvage": "Mk 5 Neuro-Saav Electrobinoculars Salvage",
  "052Salvage": "Mk 4 TaggeCo Holo Lens Salvage",
  "053": "Mk 3 Arakyd Droid Caller",
  "053Salvage": "Mk 3 Arakyd Droid Caller Salvage",
  "054Salvage": "Mk 5 Loronar Power Cell Salvage",
  "055Prototype": "Mk 4 Fabritech Data Pad Prototype",
  "055PrototypeSalvage": "Mk 4 Fabritech Data Pad Prototype Salvage",
  "056Prototype": "Mk 5 BioTech Implant Prototype",
  "056PrototypeSalvage": "Mk 5 BioTech Implant Prototype Salvage",
  "057": "Mk 1 Athakam Medpac",
  "057Salvage": "Mk 1 Athakam Medpac Salvage",
  "058Salvage": "Mk 1 Chedak Comlink Salvage",
  "060": "Mk 2 Merr-Sonn Thermal Detonator",
  "061Prototype": "Mk 6 BlasTech Weapon Mod Prototype",
  "061PrototypeSalvage": "Mk 6 BlasTech Weapon Mod Prototype Salvage",
  "062Salvage": "Mk 5 BAW Armor Mod Salvage",
  "063Prototype": "Mk 5 TaggeCo Holo Lens Prototype",
  "063PrototypeSalvage": "Mk 5 TaggeCo Holo Lens Prototype Salvage",
  "064PrototypeSalvage": "Mk 4 Nubian Security Scanner Prototype Salvage",
  "065Salvage": "Mk 6 Loronar Power Cell Salvage",
  "067": "Mk 3 Nubian Design Tech",
  "068": "Mk 3 Chiewab Hypo Syringe",
  "068PrototypeSalvage": "Mk 3 Chiewab Hypo Syringe Prototype Salvage",
  "069Prototype": "Mk 2 Chedak Comlink Prototype",
  "069PrototypeSalvage": "Mk 2 Chedak Comlink Prototype Salvage",
  "071": "Mk 1 Carbanti Sensor Array",
  "071Prototype": "Mk 1 Carbanti Sensor Array Prototype",
  "071PrototypeSalvage": "Mk 1 Carbanti Sensor Array Prototype Salvage",
  "072": "Mk 3 Merr-Sonn Thermal Detonator",
  "072Prototype": "Mk 3 Merr-Sonn Thermal Detonator Prototype",
  "072PrototypeSalvage": "Mk 3 Merr-Sonn Thermal Detonator Prototype Salvage",
  "073PrototypeSalvage": "Mk 7 BlasTech Weapon Mod Prototype Salvage",
  "075PrototypeSalvage": "Mk 6 TaggeCo Holo Lens Prototype Salvage",
  "076Salvage": "Mk 6 Fabritech Data Pad Salvage",
  "078": "Mk 2 Sienar Holo Projector",
  "078PrototypeSalvage": "Mk 2 Sienar Holo Projector Prototype Salvage",
  "080": "Mk 1 Zaltin Bacta Gel",
  "080Prototype": "Mk 1 Zaltin Bacta Gel Prototype",
  "080PrototypeSalvage": "Mk 1 Zaltin Bacta Gel Prototype Salvage",
  "081": "Mk 2 Athakam Medpac",
  "083": "Mk 2 Carbanti Sensor Array",
  "084PrototypeSalvage": "Mk 4 Merr-Sonn Thermal Detonator Prototype Salvage",
  "085Prototype": "Mk 7 BAW Armor Mod Prototype",
  "085PrototypeSalvage": "Mk 7 BAW Armor Mod Prototype Salvage",
  "086PrototypeSalvage": "Mk 6 Neuro-Saav Electrobinoculars Prototype Salvage",
  "087PrototypeSalvage": "Mk 5 Nubian Security Scanner Prototype Salvage",
  "088": "Mk 7 Loronar Power Cell",
  "090PrototypeSalvage": "Mk 5 Nubian Design Tech Prototype Salvage",
  "091Salvage": "Mk 4 SoroSuub Keypad Salvage",
  "092Salvage": "Mk 4 Arakyd Droid Caller Salvage",
  "093Prototype": "Mk 4 Chiewab Hypo Syringe Prototype",
  "093PrototypeSalvage": "Mk 4 Chiewab Hypo Syringe Prototype Salvage",
  "094PrototypeSalvage": "Mk 6 BioTech Implant Prototype Salvage",
  "095Salvage": "Mk 4 A/KT Stun Gun Salvage",
  "096PrototypeSalvage": "Mk 4 CEC Fusion Furnace Prototype Salvage",
  "097PrototypeSalvage": "Mk 8 BlasTech Weapon Mod Prototype Salvage",
  "100PrototypeSalvage": "Mk 6 Nubian Security Scanner Prototype Salvage",
  "101Salvage": "Mk 5 SoroSuub Keypad Salvage",
  "102Salvage": "Mk 3 Sienar Holo Projector Salvage",
  "103PrototypeSalvage": "Mk 2 Zaltin Bacta Gel Prototype Salvage",
  "104Prototype": "Mk 5 Chiewab Hypo Syringe Prototype",
  "104PrototypeSalvage": "Mk 5 Chiewab Hypo Syringe Prototype Salvage",
  "106": "Mk 3 Chedak Comlink",
  "106PrototypeSalvage": "Mk 3 Chedak Comlink Prototype Salvage",
  "108Salvage": "Mk 3 Carbanti Sensor Array Salvage",
  "112Salvage": "Mk 3 Czerka Stun Cuffs Salvage",
  "113Salvage": "Mk 6 Chiewab Hypo Syringe Salvage",
  "114PrototypeSalvage": "Mk 7 BioTech Implant Prototype Salvage",
  "116PrototypeSalvage": "Mk 4 Chedak Comlink Prototype Salvage",
  "117PrototypeSalvage": "Mk 5 A/KT Stun Gun Prototype Salvage",
  "119PrototypeSalvage": "Mk 4 Carbanti Sensor Array Prototype Salvage",
  "120PrototypeSalvage": "Mk 5 Merr-Sonn Thermal Detonator Prototype Salvage",
  "123Component": "Mk 8 Neuro-Saav Electrobinoculars Component",
  "123Salvage": "Mk 8 Neuro-Saav Electrobinoculars Salvage",
  "129Component": "Mk 8 BioTech Implant Component",
  "129Salvage": "Mk 8 BioTech Implant Salvage",
  "130Component": "Mk 5 Athakam Medpac Component",
  "130Salvage": "Mk 5 Athakam Medpac Salvage",
  "131Salvage": "Mk 7 Merr-Sonn Shield Generator Salvage",
  "133Component": "Mk 10 BlasTech Weapon Mod Component",
  "133Salvage": "Mk 10 BlasTech Weapon Mod Salvage",
  "135Salvage": "Mk 5 Arakyd Droid Caller Salvage",
  "136Salvage": "Mk 5 CEC Fusion Furnace Salvage",
  "138Component": "Mk 9 Fabritech Data Pad Component",
  "138Salvage": "Mk 9 Fabritech Data Pad Salvage",
  "139Salvage": "Mk 4 Sienar Holo Projector Salvage",
  "140Salvage": "Mk 3 Zaltin Bacta Gel Salvage",
  "143Salvage": "Mk 6 CEC Fusion Furnace Salvage",
  "144Salvage": "Mk 6 Merr-Sonn Thermal Detonator Salvage",
  "145Salvage": "Mk 7 Nubian Security Scanner Salvage",
  "146Salvage": "Mk 6 Nubian Design Tech Salvage",
  "147Salvage": "Mk 8 Nubian Security Scanner Salvage",
  "148Salvage": "Mk 7 Nubian Design Tech Salvage",
  "149Salvage": "Mk 6 Arakyd Droid Caller Salvage",
  "150Salvage": "Mk 4 Zaltin Bacta Gel Salvage",
  "151Salvage": "Mk 7 Chiewab Hypo Syringe Salvage",
  "152Salvage": "Mk 6 Athakam Medpac Salvage",
  "153Salvage": "Mk 9 BioTech Implant Salvage",
  "154Salvage": "Mk 7 CEC Fusion Furnace Salvage",
  "155Salvage": "Mk 6 Carbanti Sensor Array Salvage",
  "156Salvage": "Mk 7 Merr-Sonn Thermal Detonator Salvage",
  "157Salvage": "Mk 8 Nubian Design Tech Salvage",
  "158": "Mk 12 ArmaTek Multi-tool",
  "158PrototypeSalvage": "Mk 12 ArmaTek Multi-tool Prototype Salvage",
  "158Salvage": "Mk 9 Neuro-Saav Electrobinoculars Salvage",
  "159PrototypeSalvage": "Mk 12 ArmaTek Armor Plating Prototype Salvage",
  "159Salvage": "Mk 10 TaggeCo Holo Lens Salvage",
  "160PrototypeSalvage": "Mk 12 ArmaTek Bayonet Prototype Salvage",
  "160Salvage": "Mk 11 BlasTech Weapon Mod Salvage",
  "161PrototypeSalvage": "Mk 12 ArmaTek Tactical Data Prototype Salvage",
  "161Salvage": "Mk 10 Neuro-Saav Electrobinoculars Salvage",
  "162PrototypeSalvage": "Mk 12 ArmaTek Visor Prototype Salvage",
  "163PrototypeSalvage": "Mk 12 ArmaTek Wrist Band Prototype Salvage",
  "164PrototypeSalvage": "Mk 12 ArmaTek Cybernetics Prototype Salvage",
  "165PrototypeSalvage": "Mk 12 ArmaTek Medpac Prototype Salvage",
  "166PrototypeSalvage": "Mk 12 ArmaTek Thermal Detonator Prototype Salvage",
  "166PrototypeSalvage_V2": "Mk 12 Czerka Sensor Array Prototype Salvage",
  "167PrototypeSalvage": "Mk 12 ArmaTek Key Pad Prototype Salvage",
  "167PrototypeSalvage_V2": "Mk 12 Czerka Security Scanner Prototype Salvage",
  "168PrototypeSalvage": "Mk 12 ArmaTek Fusion Furnace Prototype Salvage",
  "169PrototypeSalvage": "Mk 12 ArmaTek Data Pad Prototype Salvage",
  "169PrototypeSalvage_V2": "Mk 12 Czerka Shield Generator Prototype Salvage",
  "171PrototypeSalvage": "Mk 12 ArmaTek Stun Gun Prototype Salvage",
  "171PrototypeSalvage_V2": "Mk 12 Czerka Hypo Syringe Prototype Salvage",
  "172Salvage": "Mk 7 Kyrotech Shock Prod Prototype Salvage",
  "173": "Mk 9 Kyrotech Battle Computer",
  "173Salvage": "Mk 9 Kyrotech Battle Computer Prototype Salvage",
  "174": "Mk 7 Kyrotech Power Converter",
  "174Ingredient_Salvage": "Injector Cell Salvage",
  "175Ingredient_Salvage": "Injector Handle Salvage",
  "176Ingredient_Salvage": "Injector Head Salvage",
};

const MATERIAL_NAMES = {
  "MOD_SLICING_PROMOTION_MATERIAL_T5_TO_T6": "Mk 2 Pulse Modulator",
  "MOD_SLICING_SALVAGE_TIER05_01": "Mk 1 Bonding Pin",
  "MOD_SLICING_SALVAGE_TIER05_02": "Mk 1 Fusion Disk",
  "MOD_SLICING_SALVAGE_TIER05_03": "Mk 1 Power Flow Control Chip",
  "MOD_SLICING_SALVAGE_TIER05_04": "Mk 1 Fusion Coil",
  "MOD_SLICING_SALVAGE_TIER05_05": "Mk 1 Amplifier",
  "MOD_SLICING_SALVAGE_TIER05_06": "Mk 1 Capacitor",
  "MOD_SLICING_SALVAGE_TIER06_01": "Mk 2 Circuit Breaker Module",
  "MOD_SLICING_SALVAGE_TIER06_02": "Mk 2 Thermal Exchange Unit",
  "MOD_SLICING_SALVAGE_TIER06_03": "Mk 2 Variable Resistor",
  "MOD_SLICING_SALVAGE_TIER06_04": "Mk 2 Microprocessor",
  "RM_001": "Fragmented Signal Data",
  "RM_002": "Incomplete Signal Data",
  "RM_003": "Flawed Signal Data",
  "RM_004": "Corrupted Signal Data",
  "SCV_001": "Carbonite Circuit Board",
  "SCV_001_SURPLUS": "Carbonite Circuit Board Surplus",
  "SCV_002": "Bronzium Wiring",
  "SCV_002_SURPLUS": "Bronzium Wiring Surplus",
  "SCV_003": "Chromium Transistor",
  "SCV_004": "Aurodium Heatsink",
  "SCV_005": "Electrium Conductor",
  "SCV_005_SURPLUS": "Electrium Conductor Surplus",
  "SCV_006": "Zinbiddle Card",
  "SCV_007": "Impulse Detector",
  "SCV_008": "Aeromagnifier",
  "SCV_009": "Gyrda Keypad",
  "SCV_010": "Droid Brain",
  "SCV_011": "Coaxial Servomotor",
  "ability_mat_A": "Ability Material Mk I",
  "ability_mat_B": "Ability Material Mk II",
  "ability_mat_C": "Ability Material Mk III",
  "ability_mat_D": "Ability Material Omega",
  "ability_mat_E": "Ability Material Zeta",
  "ability_mat_F": "Ability Material Omicron",
  "coaxium": "Coaxium",
  "datacron_set_31_reroll_1": "Converter Mk1",
  "datacron_set_31_reroll_2": "Converter Mk2",
  "datacron_set_31_reroll_3": "Converter Mk3",
  "datacron_set_31_upgrade_1": "Coding Mk1",
  "datacron_set_31_upgrade_2": "Coding Mk2",
  "datacron_set_31_upgrade_3": "Coding Mk3",
  "datacron_set_32_reroll_1": "Downlink Mk1",
  "datacron_set_32_reroll_3": "Downlink Mk3",
  "datacron_set_32_upgrade_1": "Deboss Mk1",
  "datacron_set_32_upgrade_2": "Deboss Mk2",
  "datacron_set_32_upgrade_3": "Deboss Mk3",
  "datacron_set_33_reroll_1": "Alteration Mk1",
  "datacron_set_33_reroll_2": "Alteration Mk2",
  "datacron_set_33_upgrade_1": "Acumen Mk1",
  "datacron_set_33_upgrade_2": "Acumen Mk2",
  "datacron_set_33_upgrade_3": "Acumen Mk3",
  "datacron_set_34_reroll_1": "Breakdown Mk1",
  "datacron_set_34_reroll_2": "Breakdown Mk2",
  "datacron_set_34_reroll_3": "Breakdown Mk3",
  "era_upgrade_advanced_1": "Mk I Basic Performance Core",
  "era_upgrade_advanced_2": "Mk II Improved Performance Core",
  "era_upgrade_advanced_3": "Mk III Advanced Performance Core",
  "era_upgrade_basic_1": "Mk I Grek Ability Module",
  "era_upgrade_basic_2": "Mk II Forn Ability Module",
  "era_upgrade_basic_3": "Mk III Esk Ability Module",
  "era_upgrade_special_1": "Zerek Ability Module",
  "ship-xp-mat-four-star": "T4 Enhancement Droid",
  "ship-xp-mat-one-star": "T1 Enhancement Droid",
  "ship-xp-mat-three-star": "T3 Enhancement Droid",
  "ship-xp-mat-two-star": "T2 Enhancement Droid",
  "shipability_mat_A": "Ship Ability Material Mk I",
  "shipability_mat_B": "Ship Ability Material Mk II",
  "shipability_mat_C": "Ship Ability Material Mk III",
  "shipability_mat_D": "Ship Ability Material Omega",
  "shipability_mat_hardware_systems": "Reinforcement Materials",
  "shipability_mat_prestige": "Prestige",
  "unitshard_4LOM": "4-LOM",
  "unitshard_50RT": "50R-T",
  "unitshard_AAYLASECURA": "Aayla Secura",
  "unitshard_AMILYNHOLDO": "Amilyn Holdo",
  "unitshard_APPO": "CC-1119 \"Appo\"",
  "unitshard_ARC170CLONESERGEANT": "Clone Sergeant's ARC-170",
  "unitshard_ARC170REX": "Rex's ARC-170",
  "unitshard_ARMORER": "The Armorer",
  "unitshard_ASAJJDARKDISCIPLE": "Asajj Ventress (Dark Disciple)",
  "unitshard_ASAJVENTRESS": "Asajj Ventress",
  "unitshard_B1BATTLEDROIDV2": "B1 Battle Droid",
  "unitshard_B2SUPERBATTLEDROID": "B2 Super Battle Droid",
  "unitshard_BADBATCHECHO": "Echo",
  "unitshard_BADBATCHHUNTER": "Hunter",
  "unitshard_BADBATCHTECH": "Tech",
  "unitshard_BADBATCHWRECKER": "Wrecker",
  "unitshard_BARRISSOFFEE": "Barriss Offee",
  "unitshard_BASTILASHAN": "Bastila Shan",
  "unitshard_BASTILASHANDARK": "Bastila Shan (Fallen)",
  "unitshard_BATCHERS3": "Batcher",
  "unitshard_BAZEMALBUS": "Baze Malbus",
  "unitshard_BENSOLO": "Ben Solo",
  "unitshard_BISHOP": "Colonel Ward",
  "unitshard_BOBAFETTSCION": "Boba Fett, Scion of Jango",
  "unitshard_BODHIROOK": "Bodhi Rook",
  "unitshard_BOOMADIER": "Gungan Boomadier",
  "unitshard_BOSSNASS": "Boss Nass",
  "unitshard_BRUTUS": "Brutus",
  "unitshard_BT1": "BT-1",
  "unitshard_CAPTAINTARPALS": "Captain Tarpals",
  "unitshard_CARSONTEVA": "Captain Carson Teva",
  "unitshard_CC2224": "CC-2224 \"Cody\"",
  "unitshard_CEREJUNDA": "Cere Junda",
  "unitshard_CHIEFCHIRPA": "Chief Chirpa",
  "unitshard_CHIEFNEBIT": "Chief Nebit",
  "unitshard_CHIRRUTIMWE": "Chirrut Îmwe",
  "unitshard_CHOPPERS3": "Chopper",
  "unitshard_CINTA": "Cinta Kaz",
  "unitshard_CLONEWARSCHEWBACCA": "Clone Wars Chewbacca",
  "unitshard_COBBVANTH": "Cobb Vanth",
  "unitshard_COLONELSTARCK": "Colonel Starck",
  "unitshard_COMMANDERAHSOKA": "Commander Ahsoka Tano",
  "unitshard_CORUSCANTUNDERWORLDPOLICE": "Coruscant Underworld Police",
  "unitshard_COUNTDOOKU": "Count Dooku",
  "unitshard_CROSSHAIRS3": "Crosshair (Scarred)",
  "unitshard_CT210408": "CT-21-0408 \"Echo\"",
  "unitshard_DARKREY": "Rey (Dark Side Vision)",
  "unitshard_DARTHBANE": "Darth Bane",
  "unitshard_DARTHMALGUS": "Darth Malgus",
  "unitshard_DARTHSION": "Darth Sion",
  "unitshard_DARTHTRAYA": "Darth Traya",
  "unitshard_DATHCHA": "Dathcha",
  "unitshard_DEATHTROOPER": "Death Trooper",
  "unitshard_DEDRAMEERO": "Dedra Meero",
  "unitshard_DIRECTORKRENNIC": "Director Krennic",
  "unitshard_DISGUISEDCLONETROOPER": "Disguised Clone Trooper",
  "unitshard_DROIDEKA": "Droideka",
  "unitshard_EBONHAWK": "Ebon Hawk",
  "unitshard_EETHKOTH": "Eeth Koth",
  "unitshard_EMPERORSSHUTTLE": "Emperor's Shuttle",
  "unitshard_ENFYSNEST": "Enfys Nest",
  "unitshard_EPIXFINN": "Resistance Hero Finn",
  "unitshard_EPIXPOE": "Resistance Hero Poe",
  "unitshard_EZRAEXILE": "Ezra Bridger (Exile)",
  "unitshard_FINN": "Finn",
  "unitshard_FIRSTORDERTIEECHELON": "TIE Echelon",
  "unitshard_FURYCLASSINTERCEPTOR": "Fury-class Interceptor",
  "unitshard_GARSAXON": "Gar Saxon",
  "unitshard_GAUNTLETSTARFIGHTER": "Gauntlet Starfighter",
  "unitshard_GENERALSYNDULLA": "General Syndulla",
  "unitshard_GEONOSIANSTARFIGHTER1": "Sun Fac's Geonosian Starfighter",
  "unitshard_GEONOSIANSTARFIGHTER2": "Geonosian Soldier's Starfighter",
  "unitshard_GEONOSIANSTARFIGHTER3": "Geonosian Spy's Starfighter",
  "unitshard_GOPHERANTS": "Grogu & Anzellans",
  "unitshard_GREEDO": "Greedo",
  "unitshard_GUNGANPHALANX": "Gungan Phalanx",
  "unitshard_HK47": "HK-47",
  "unitshard_HONDO": "Hondo Ohnaka",
  "unitshard_HOTHREBELSOLDIER": "Hoth Rebel Soldier",
  "unitshard_HUMANTHUG": "Mob Enforcer",
  "unitshard_HUNTERS3": "Hunter (Mercenary)",
  "unitshard_HUYANG": "Huyang",
  "unitshard_HYENABOMBER": "Hyena Bomber",
  "unitshard_IDENVERSIOEMPIRE": "Iden Versio",
  "unitshard_IMAGUNDI": "Ima-Gun Di",
  "unitshard_IMPERIALPROBEDROID": "Imperial Probe Droid",
  "unitshard_IMPERIALSUPERCOMMANDO": "Imperial Super Commando",
  "unitshard_INQUISITORBARRISS": "Inquisitor Barriss",
  "unitshard_ITHANO": "Captain Ithano",
  "unitshard_JANGOFETT": "Jango Fett",
  "unitshard_JAWA": "Jawa",
  "unitshard_JAWAENGINEER": "Jawa Engineer",
  "unitshard_JAWASCAVENGER": "Jawa Scavenger",
  "unitshard_JEDIKNIGHTGUARDIAN": "Jedi Knight Guardian",
  "unitshard_JEDISTARFIGHTERCONSULAR": "Jedi Consular's Starfighter",
  "unitshard_JOCASTANU": "Jocasta Nu",
  "unitshard_JOLEEBINDO": "Jolee Bindo",
  "unitshard_KITFISTO": "Kit Fisto",
  "unitshard_KIX": "Kix",
  "unitshard_KLEYA": "Kleya Marki",
  "unitshard_KRRSANTAN": "Krrsantan",
  "unitshard_KXSECURITYDROID": "KX Security Droid",
  "unitshard_LEIAJEDITRAINING": "Leia (Jedi Training)",
  "unitshard_LOBOT": "Lobot",
  "unitshard_LOGRAY": "Logray",
  "unitshard_LUKESTARKILLER": "Starkiller (Luke Concept)",
  "unitshard_LUMINARAUNDULI": "Luminara Unduli",
  "unitshard_LUTHENRAEL": "Luthen Rael",
  "unitshard_MAGMATROOPER": "Magmatrooper",
  "unitshard_MAGNAGUARD": "IG-100 MagnaGuard",
  "unitshard_MAJORPARTAGAZ": "Major Partagaz",
  "unitshard_MARAJADESKYWALKER": "Mara Jade Skywalker",
  "unitshard_MARAUDER": "Marauder",
  "unitshard_MARROK": "Marrok",
  "unitshard_MAUL": "Darth Maul",
  "unitshard_MAULS7": "Maul",
  "unitshard_MAZKANATA": "Maz Kanata",
  "unitshard_MERRIN": "Merrin",
  "unitshard_MG100STARFORTRESSSF17": "MG-100 StarFortress SF-17",
  "unitshard_MILLENNIUMFALCONEP7": "Rey's Millennium Falcon",
  "unitshard_MILLENNIUMFALCONPRISTINE": "Lando's Millennium Falcon",
  "unitshard_MISSIONVAO": "Mission Vao",
  "unitshard_MOFFGIDEONS3": "Dark Trooper Moff Gideon",
  "unitshard_MONMOTHMA": "Mon Mothma",
  "unitshard_MOTHERTALZIN": "Mother Talzin",
  "unitshard_NIGHTSISTERACOLYTE": "Nightsister Acolyte",
  "unitshard_NIGHTSISTERINITIATE": "Nightsister Initiate",
  "unitshard_NIGHTSISTERZOMBIE": "Nightsister Zombie",
  "unitshard_NUTEGUNRAY": "Nute Gunray",
  "unitshard_OMEGAS3": "Omega (Fugitive)",
  "unitshard_OUTRIDER": "Outrider",
  "unitshard_PADAWANSABINE": "Padawan Sabine Wren",
  "unitshard_PAO": "Pao",
  "unitshard_POE": "Poe Dameron",
  "unitshard_PUNISHINGONE": "Punishing One",
  "unitshard_QUEENAMIDALA": "Queen Amidala",
  "unitshard_QUIGGOLD": "Quiggold",
  "unitshard_R5D4": "R5-D4",
  "unitshard_RANGERZEB": "Zeb Orrelios (New Republic Pilot)",
  "unitshard_RAZORCREST": "Razor Crest",
  "unitshard_REMNANTSNOWCOMMANDER": "Snowtrooper Commander",
  "unitshard_RESISTANCEPILOT": "Resistance Pilot",
  "unitshard_RESISTANCETROOPER": "Resistance Trooper",
  "unitshard_REY": "Rey (Scavenger)",
  "unitshard_ROGUEONESHIP": "Rogue One",
  "unitshard_ROSETICO": "Rose Tico",
  "unitshard_SATELESHAN": "Satele Shan",
  "unitshard_SAWGERRERA": "Saw Gerrera",
  "unitshard_SCORCH": "RC-1262 \"Scorch\"",
  "unitshard_SCYTHE": "Scythe",
  "unitshard_SHINHATI": "Shin Hati",
  "unitshard_SHORETROOPER": "Shoretrooper",
  "unitshard_SITHASSASSIN": "Sith Assassin",
  "unitshard_SITHBOMBER": "B-28 Extinction-class Bomber",
  "unitshard_SITHINFILTRATOR": "Scimitar",
  "unitshard_SITHTROOPER": "Sith Empire Trooper",
  "unitshard_SM33": "SM-33",
  "unitshard_SMUGGLERCHEWBACCA": "Veteran Smuggler Chewbacca",
  "unitshard_STORMTROOPERLUKE": "Stormtrooper Luke",
  "unitshard_SUPREMELEADERKYLOREN": "Supreme Leader Kylo Ren",
  "unitshard_T3_M4": "T3-M4",
  "unitshard_TARFFUL": "Tarfful",
  "unitshard_TARONMALICOS": "Taron Malicos",
  "unitshard_THIRDSISTER": "Third Sister",
  "unitshard_TIEDAGGER": "TIE Dagger",
  "unitshard_TIEDEFENDER": "TIE Defender",
  "unitshard_TIEFIGHTERFOSF": "First Order SF TIE Fighter",
  "unitshard_TIEINTERCEPTOR": "TIE/IN Interceptor Prototype",
  "unitshard_TIEREAPER": "TIE Reaper",
  "unitshard_TRENCH": "Admiral Trench",
  "unitshard_TRIPLEZERO": "0-0-0",
  "unitshard_TUSKENCHIEFTAIN": "Tusken Chieftain",
  "unitshard_TUSKENRAIDER": "Tusken Raider",
  "unitshard_TUSKENSHAMAN": "Tusken Shaman",
  "unitshard_UGNAUGHT": "Ugnaught",
  "unitshard_UNDERCOVERLANDO": "Skiff Guard (Lando Calrissian)",
  "unitshard_URORRURRR": "URoRRuR'R'R",
  "unitshard_VADERDUELSEND": "Darth Vader (Duel's End)",
  "unitshard_VANE": "Vane",
  "unitshard_VANGUARDTEMPLEGUARD": "Temple Guard",
  "unitshard_VEL": "Vel Sartha",
  "unitshard_VULTUREDROID": "Vulture Droid",
  "unitshard_WATTAMBOR": "Wat Tambor",
  "unitshard_WRECKERS3": "Wrecker (Mercenary)",
  "unitshard_XWINGBLACKONE": "Poe Dameron's X-wing",
  "unitshard_XWINGRESISTANCE": "Resistance X-wing",
  "unitshard_YODACHEWBACCA": "Yoda & Chewie",
  "unitshard_YODADSV": "Yoda (Dark Side Vision)",
  "unitshard_YOUNGLANDO": "Young Lando Calrissian",
  "unitshard_YWINGCLONEWARS": "BTL-B Y-wing Starfighter",
  "unitshard_YWINGREBEL": "Rebel Y-wing",
  "unitshard_ZAALBAR": "Zaalbar",
  "unitshard_ZAMWESELL": "Zam Wesell",
  "unitshard_ZORIIBLISS_V2": "Zorii Bliss",
  "unitshard_ZUCKUSS": "Zuckuss",
  "xp-mat-five-star": "T5 Training Droid",
  "xp-mat-four-star": "T4 Training Droid",
  "xp-mat-one-star": "T1 Training Droid",
  "xp-mat-seven-star": "T7 Training Droid",
  "xp-mat-six-star": "T6 Training Droid",
  "xp-mat-three-star": "T3 Training Droid",
  "xp-mat-two-star": "T2 Training Droid",
};

// unitStatId -> display name. Resolved from enums.json (UnitStat) cross-referenced
// against Loc_ENG_US.txt.json via the UnitStat_<Name> key convention. Covers the
// full game enum, not just IDs seen in this account's mods.
const MOD_STAT_NAMES = {
  1: "Health #",
  2: "Strength",
  3: "Agility",
  4: "Intelligence",
  5: "Speed #",
  6: "Physical Damage",
  7: "Special Damage",
  8: "Armor",
  9: "Resistance",
  10: "Armor Penetration",
  11: "Resistance Penetration",
  12: "Dodge Rating",
  13: "Deflection Rating",
  14: "Physical Critical Rating",
  15: "Special Critical Rating",
  16: "Critical Damage",
  17: "Potency %",
  18: "Tenacity %",
  19: "Dodge",
  20: "Deflection",
  21: "Physical Critical Chance",
  22: "Special Critical Chance",
  23: "Armor",
  24: "Resistance",
  25: "Armor Penetration",
  26: "Resistance Penetration",
  27: "Health Steal",
  28: "Protection #",
  29: "Protection Ignore",
  30: "Health Regeneration",
  31: "Physical Damage",
  32: "Special Damage",
  33: "Physical Accuracy",
  34: "Special Accuracy",
  35: "Physical Critical Avoidance",
  36: "Special Critical Avoidance",
  37: "Physical Accuracy",
  38: "Special Accuracy",
  39: "Physical Critical Avoidance",
  40: "Special Critical Avoidance",
  41: "Offense #",
  42: "Defense #",
  43: "Defense Penetration #",
  44: "Evasion #",
  45: "Critical Chance #",
  46: "Accuracy #",
  47: "Critical Avoidance #",
  48: "Offense %",
  49: "Defense %",
  50: "Defense Penetration %",
  51: "Evasion %",
  52: "Accuracy %",
  53: "Critical Chance %",
  54: "Critical Avoidance %",
  55: "Health %",
  56: "Protection %",
  57: "Speed %",
  58: "Counter Attack",
  59: "Taunt",
  60: "Defense Penetration",
  61: "Mastery",
};

// currency (enum int) -> display name. NOT auto-resolved -- the CurrencyType enum
// only exposes internal category names (GRIND, PREMIUM, etc.), no direct localization
// key like equipment/material had. Best-effort from context; entries marked (?) need
// verification/correction -- you'll know these better than any data file will.
const CURRENCY_NAMES = {
  1: "Credits",
  2: "Crystals",
  4: "Ally Points",
  10: "Squad Arena Tokens",
  11: "Cantina Battle Tokens",
  12: "Fleet Arena Tokens",
  14: "Galactic War Tokens",
  15: "Sim Tickets",
  16: "Shard Store Tokens",
  17: "Guild Tokens",
  19: "Ship Building Materials",
  32: "Mk I Guild Event Tokens",
  33: "Championship Tokens",
  34: "Mk II Guild Event Tokens",
  35: "Galactic Bundle Currency (?)",
  36: "Light Side Currency",
  37: "Dark Side Currency",
  39: "Conquest Credits",
  40: "Data-caches",
  41: "Micro Attenuators",
  42: "Mk III Guild Event Tokens",
  43: "Mk I Raid Tokens",
  44: "Mk II Raid Tokens",
  45: "Mk III Raid Tokens",
  47: "Legend Tokens",
  48: "Episode Currency",
  49: "Era Currency",
  50: "Era Level Currency",
};